alias x='exit'
alias ag='sudo apt-get'
alias zshrc='nvim ~/.zshrc'
alias vimrc='nvim ~/.config/nvim/init.vim'
alias sr='cd ~/sources'
alias ali='nvim ~/.oh-my-zsh/lib/alias.zsh'
alias mkenv='mkvirtualenv'
alias mkpr='mkproject'
alias wo='workon'
alias da='deactivate'
alias rmvenv='rmvirtualenv'
alias ~='cd ~'
alias crc='cargo rustc -- -C link-args=-nostartfiles'
alias cde='~/Documents/repos/VSCode-linux-x64/code'
